name: Build on push to branch

on:
  push:
    branches: [main]

# implicitely set all other permissions to none
permissions:
  checks: write # test.yml
  contents: read # debos.yml lava-schema-check.yml test.yml
  packages: read # test.yml
  pull-requests: write # test.yml

jobs:
  build-daily:
    uses: ./.github/workflows/debos.yml
  schema-check:
    uses: ./.github/workflows/lava-schema-check.yml
  test:
    uses: ./.github/workflows/test.yml
    needs: [build-daily, schema-check]
    secrets: inherit
    with:
      url: ${{ needs.build-daily.outputs.artifacts_url }}
