name: Daily Build

on:
  # run daily at 8:30am
  schedule:
    - cron: '30 8 * * *'
  # allow manual runs
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-daily:
    uses: ./.github/workflows/debos.yml
  test-daily:
    uses: ./.github/workflows/test.yml
    needs: build-nightly
    secrets: inherit
    with:
      url: ${{ needs.build-daily.outputs.artifacts_url }}
