name: Daily Build

on:
  # run daily at 8:30am
  schedule:
    - cron: '30 8 * * *'
  # allow manual runs
  workflow_dispatch:

# implicitely set all other permissions to none
permissions:
  contents: read # debos.yml

jobs:
  build-daily:
    # don't run cron from forks of the main repository or from other branches
    if: github.repository == 'qualcomm-linux/qcom-deb-images' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/debos.yml

  test-daily:
    # don't run cron from forks of the main repository or from other branches
    if: github.repository == 'qualcomm-linux/qcom-deb-images' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/test.yml
    needs: build-daily
    secrets: inherit
    with:
      url: ${{ needs.build-daily.outputs.artifacts_url }}
