name: Build on PR

on:
  pull_request:

# implicitely set all other permissions to none
permissions:
  checks: write # test.yml
  contents: read # debos.yml lava-schema-check.yml test.yml
  packages: read # test.yml
  pull-requests: write # test.yml

jobs:
  event-file:
    name: "Upload event file"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Event File
        path: ${{ github.event_path }}

  build-pr:
    uses: ./.github/workflows/debos.yml
  schema-check:
    uses: ./.github/workflows/lava-schema-check.yml
