name: Build on push to branch

on:
  push:
    branches: [main]

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read

jobs:
  build-daily:
    uses: ./.github/workflows/debos.yml
  schema-check:
    uses: ./.github/workflows/lava-schema-check.yml
  test:
    uses: ./.github/workflows/test.yml
    needs: [build-daily, schema-check]
    secrets: inherit
    with:
      url: ${{ needs.build-daily.outputs.artifacts_url }}
